# Generated by Django 4.1 on 2022-08-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='last_seen',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='profile_image',
            field=models.ImageField(default=None, upload_to='forum/images'),
        ),
    ]
