# Generated by Django 4.1 on 2022-08-24 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0002_alter_usermodel_last_seen_and_more'),
        ('mycontent', '0003_votemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votemodel',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='myauth.usermodel'),
        ),
    ]
